dataService:
  image:
    repository: renku/renku-data-service
    tag:
  dataTasks:
    image:
      repository: renku/data-service-data-tasks
      tag:
  backgroundJobs:
    image:
      repository: renku/data-service-background-jobs
      tag:
  k8sWatcher:
    image:
      repository: renku/data-service-k8s-watcher
      tag:
secretsStorage:
  image:
    repository: renku/secrets-storage
    tag:
logging:
  logFormatStyle: plain
